// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BossMandados.iOS
{
	public partial class CustomTextField : UITextField
	{
		public CustomTextField (IntPtr handle) : base (handle)
		{
		}
	}
}
